object: orig/eu/sys/main.dol
hash: 10d34dbf901e5d6547718176303a6073ee80dda2
symbols: config/eu/symbols.txt
splits: config/eu/splits.txt

mw_comment_version: 15
symbols_known: true
fill_gaps: true

block_relocations:
# extab contains these values, but they're not dtors
- target: 0x80080000
- target: 0x800A0000
- target: 0x804A0000
