object: orig/us/sys/main.dol
hash: 214b15173fa3bad23a067476d58d3933ad7037b7
symbols: config/us/symbols.txt
splits: config/us/splits.txt

mw_comment_version: 15
symbols_known: true
fill_gaps: true

block_relocations:
# extab contains these values, but they're not dtors
- target: 0x80080000
- target: 0x800A0000
- target: 0x804A0000
